name: Deploy to Ubuntu Server

on:
  push:
    branches:
      - main  # Cambia 'main' por el nombre de tu rama principal si es diferente

jobs:
  deploy:
    runs-on: ubuntu-latest  # Utiliza la versión más reciente de Ubuntu

    steps:
      - name: Checkout code
        uses: actions/checkout@v2  # Acción para clonar el repositorio

      - name: SSH to server and update code
        uses: appleboy/ssh-action@master  # Acción para conectar por SSH y ejecutar comandos
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          password: ${{ secrets.SERVER_PASSWORD }}  # Variable de secreto para la contraseña
          script: |
            cd /root/controlSaldos
            git pull origin master  # Cambia 'main' por el nombre de tu rama principal si es diferente
